version: '3.8'

services:
    pgsql:
      image: postgres:16
      restart: unless-stopped
      # Uncomment the following line to enable query logging
      # Then restart the container.
      # command: ['postgres', '-c', 'log_statement=all']
      environment:
        - POSTGRES_DB=pgsql
        - POSTGRES_USER=prisma
        - POSTGRES_PASSWORD=prisma
      ports:
        - '5432:5432'
      healthcheck:
        # specifying user and database is needed to avoid `FATAL:  role "root" does not exist`
        # spam in the logs
        test: [ 'CMD', 'pg_isready', '-U', 'prisma', '-d', 'pgsql' ]
        interval: 5s
        timeout: 2s
        retries: 20
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 800M
          reservations:
            cpus: '0.5'
            memory: 800M

    web:
      build: ./project
      ports:
        - "8000:8000"
      command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
      volumes:
        - ./project:/usr/src/app
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
        - DATABASE_URL=postgresql://prisma:prisma@pgsql:5432/pgsql
      depends_on:
        - redis
        - pgsql
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 800M
          reservations:
            cpus: '0.5'
            memory: 600M


    worker:
      build: ./project
      command: celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
      depends_on:
        - web
        - redis

    redis:
      image: redis:7
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 50M
          reservations:
            cpus: '0.25'
            memory: 40M

    dashboard:
      build: ./project
      command: celery --broker=redis://redis:6379/0 flower --port=5555
      ports:
        - 5556:5555
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
      depends_on:
        - web
        - redis
        - worker
